import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // <--- 🔴 必须有这一行！检查路径是否正确

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JD Agent - AI 面试助手",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className={inter.className}>{children}</body>
    </html>
  );
}