import type { Metadata } from "next";
import "./globals.css"; // <--- 🔴 必须有这一行！检查路径是否正确
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "JD Agent - AI 面试助手",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="zh">
      {/* 防止浏览器或扩展在 body 上注入额外属性导致的水合警告 */}
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}