[pytest]
# 测试文件路径
testpaths = src/test
# 测试文件命名模式
python_files = test_*.py
# 日志级别
log_cli = 1
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)s | %(message)s
log_cli_datefmt = %Y-%m-%d %H:%M:%S
# 忽略警告
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
# 启用异步测试支持
asyncio_mode = auto